version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Markdown Linter
          command: gem install mdl
      - run:
          name: Check the GoogleCloudPlatform Dir for Markdown rules
          command: mdl docs/
